[package]
name = "shared"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = { version = "0.4.42", features = ["serde"] }
# csv = "1.3.1"
# anyhow = "1.0.99"
# thiserror = "2.0.16"
tracing = "0.1.41"
log = "0.4.28"